export const EPL_TEAM_LOGO_MAP: Record<string, string> = {
  "Arsenal": "Arsenal",
  "Aston Villa": "Aston Villa",
  "Bournemouth": "AFC Bournemouth",
  "Brentford": "Brentford",
  "Brighton": "Brighton & Hove Albion",
  "Chelsea": "Chelsea",
  "Crystal Palace": "Crystal Palace",
  "Everton": "Everton",
  "Fulham": "Fulham",
  "Liverpool": "Liverpool",
  "Manchester City": "Manchester City",
  "Manchester Utd": "Manchester United",
  "Newcastle Utd": "Newcastle United",
  "Nott'ham Forest": "Nottingham Forest",
  "Southampton": "Southampton",
  "Tottenham": "Tottenham Hotspur",
  "West Ham":  "West Ham United",
  "Wolves" : "Wolverhampton Wanderers",
  "Leeds United": "Leeds United",
  "Burnley": "burnley",
  "Sunderland": "Sunderland"
};
export const EPL_TEAM_ALIAS: Record<string, string> = {
  "Arsenal": "Arsenal",
  "Aston Villa": "Aston Villa",
  "AFC Bournemouth": "Bournemouth",
  "Brentford": "Brentford",
  "Brighton & Hove Albion": "Brighton",
  "Chelsea": "Chelsea",
  "Crystal Palace": "Crystal Palace",
  "Everton": "Everton",
  "Fulham": "Fulham",
  "Liverpool": "Liverpool",
  "Manchester City": "Manchester City",
  "Manchester United": "Manchester Utd",
  "Newcastle United": "Newcastle Utd",
  "Nottingham Forest": "Nott'ham Forest",
  "Southampton": "Southampton",
  "Tottenham Hotspur": "Tottenham",
  "West Ham United": "West Ham",
  "Wolverhampton Wanderers": "Wolves",
  "Leeds United": "Leeds United",
  "Burnley": "Burnley",
  "Sunderland": "Sunderland"
};
